name: Build and Release Obsidian Plugin

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to create/release (e.g. v1.2.3)"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Build plugin
        run: |
          npm ci
          npm run build

      - name: Show built files
        run: |
          pwd
          ls -la

      - name: Package release archive
        run: |
          zip -r obsidian-henni-plugin.zip main.js manifest.json styles.css pdf.worker.mjs image-note-template.md pdf-note-template.md other-note-template.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref_name }}
          tag_name: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref_name }}
          fail_on_unmatched_files: true
          files: |
            main.js 
            manifest.json 
            styles.css 
            pdf.worker.mjs 
            image-note-template.md
            pdf-note-template.md
            other-note-template.md
            obsidian-henni-plugin.zip
        
